sudo: false

git:
  depth: 5

addons:
  apt:
    packages:
      - gcc
      - git
      - wget
      - make
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial

language: cpp
dist: trusty

script: ./.travis.sh

jobs:
  include:
    - stage: RX
      name: RX
      env: TARGETS_FILTER=_rx
    - stage: TX
      name: TX
      env: TARGETS_FILTER=_tx
    - stage: TXRX
      name: TXRX
      env: TARGETS_FILTER=_txrx
