sudo: false

git:
  depth: 5
  quiet: true

addons:
  apt:
    packages:
      - gcc
      - git
      - wget
      - make
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial

language: cpp
dist: trusty

jobs:
  include:
    - stage: run
      script: ./.travis.sh _tx
    -
      script: ./.travis.sh _rx
    -
      script: ./.travis.sh _txrx
