sudo: false

git:
  depth: 5
  quiet: true

addons:
  apt:
    sources:
      # PPA for clang-format 8
      - llvm-toolchain-trusty
      # Required by clang-format 8
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - git
      - wget
      - make
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial
      - clang-format-8

language: cpp
dist: trusty

jobs:
  include:
    - stage: run
      script: ./.travis.sh tx
    -
      script: ./.travis.sh rx
    -
      script: ./.travis.sh txrx
