sudo: false

git:
  depth: 5

addons:
  apt:
    packages:
      - gcc
      - git
      - wget
      - make
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial

language: cpp
dist: trusty

jobs:
  include:
    - stage: run
      script: ./.travis.sh tx
    -
      script: ./.travis.sh rx
    -
      script: ./.travis.sh txrx
